config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  resources :chat_rooms, only: [:index, :show, :new, :create]
  # get '/chat_rooms/:id', to: redirect('/chat_rooms/%{id}'), as: 'chat_room'

  get 'profile/:id', to: 'users#show', as: :profile


  authenticated :user do
    root to: 'chat_rooms#index', as: :authenticated_root
  end

  root to: 'static_pages#home'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
# == Schema Information
#
# Table name: chat_rooms
#
#  id             :integer          not null, primary key
#  title          :string
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  messages_count :integer
#

class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy

  validates :title, presence: true;

  scope :recent, -> (n) { order(created_at: :DESC).limit(n) }
  scope :hot, -> { where("messages_count >= ?", 20) }

  # For will_paginate
  self.per_page = 10

  def created_time
    created_at.strftime('%H:%M %d %B %Y')
  end

  def owner
    User.find(user_id)
  end
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id           :integer          not null, primary key
#  body         :text
#  user_id      :integer
#  chat_room_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room, counter_cache: true

  validates :body,
            presence: true,
            length: {
              minimum: 2,
              maximum: 999
            }

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  role                   :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }, uniqueness: true

  def has_role?(role)
    self.role == role
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def authenticate_admin_user!
    authenticate_user!
    unless current_user.has_role?('Admin')
      flash[:alert] = 'You are not authorized to access this resource!'
      redirect_to root_path
    end
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  before_action :authenticate_user!, only: [ :new, :create ]

  layout 'msg_board', only: [ :show ]

  def index
    @chat_rooms = ChatRoom.paginate(page: params[:page])
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message =Message.new
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room build successfully~'
      redirect_to chat_rooms_path
    else
      flash[:error] = 'Some error(s) happened!'
      render 'new'
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'static_home'

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email)
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/_chat_room.html.erb
<!-- <span id="some-span" data-no-turbolink> -->
<!-- method: :get -->

<%= link_to chat_room_path(chat_room) do %>
  <li>
    <div class="room-title">
      <%= chat_room.title %>
    </div>

    <div class="room-detail">
      <div class="row">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <span class="small-gravatar">
            <%= gravatar_for chat_room.owner %>
          </span>

          <span class="notes">
            <%= "#{chat_room.owner.name.capitalize} created at #{chat_room.created_time}" %>
          </span>
        </div>

        <div class="col-md-offset-2 col-md-2 col-sm-offset-2 col-sm-2 col-xs-4">
          <span class="count">
            <%= pluralize(chat_room.messages_count, 'post') %>
          </span>
        </div>
      </div>

    </div>
  </li>
<% end  %>
<!-- </span> -->

app/views/chat_rooms/index.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">

    <h1 class="rooms-header page-header">
      Chat rooms
    </h1>

    <ul class="rooms">
      <%= render @chat_rooms %>
    </ul>

    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <span class="paginate">
          <%= will_paginate @chat_rooms%>
        </span>
      </div>
    </div>

    <% if user_signed_in? %>
      <div class="row">
        <div class="col-md-offset-4 col-md-4">
          <%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-highlight'%>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/chat_rooms/new.html.erb
<div class="form-page">

  <div class="row">
    <div class="col-md-offset-4 col-md-4">

      <%= render partial: 'shared/errors', locals: { item: @chat_room} %>

      <%= form_for @chat_room do |f| %>
        <div class="field form-group">
          <%= f.label :chat_room_name %>
          <%= f.text_field :title, autofocus: true, class: 'form-control' %>
        </div>

        <%= f.submit 'New chat room', class: 'btn btn-highlight' %>
      <% end %>
    </div>
  </div>

</div>

app/views/chat_rooms/show.html.erb
<%= content_for :sidebar_content do %>
  <nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <%= link_to 'Join', root_path %>
      </li>

      <% if user_signed_in?  %>
        <li>
          <%= link_to "Profile", profile_path(current_user) %>
        </li>

        <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %>
        </li>
      <% end %>

      <li>
        <%= link_to @chat_room.title.upcase, chat_room_path(@chat_room), class: 'room-title' %>
      </li>

      <li>
        <span class="normal-text">Created by</span>
        <br/>
        <%= link_to @chat_room.owner.name.capitalize, profile_path(@chat_room.owner), class: 'room-creator' %>
      </li>

      <li>
        <span class="normal-text">At</span>
        <br/>
        <span class="created_time">
          <%= @chat_room.created_time %>
        </span>
      </li>

      <!-- Todo: online users -->
      <!-- <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-fw fa-plus"></i> Online Users <span class="caret"></span></a>
           <ul class="dropdown-menu" role="menu">
           <li class="dropdown-header">Dropdown heading</li>
           <li><a href="#">Action</a></li>
           </ul>
           </li>
         -->
    </ul>
  </nav>

<% end %>

<div id="messages" class="messages-board" data-chat-room-id="<%= @chat_room.id %>" data-current-user-id="<%= current_user ? current_user.id : -1%>" >
  <%= render @chat_room.messages %>
</div>

<%= form_for @message, url: '#' do |f| %>
  <div class="form-group">
    <%= f.text_area :body, placeholder: 'message', class: 'form-control' %>
    <% if user_signed_in? %>
      <%= f.submit 'send', class: 'btn btn-highlight' %>
    <% else %>
      <%= f.submit 'Please login or sign up', class: 'btn btn-disabled', disabled: true %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/feedback_wrapper' %>

    <%= render 'shared/header' %>

    <div class="container yield-content">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/layouts/msg_board.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="msg-layout">
    <div id="wrapper" class="menuDisplayed">

      <!-- Sidebar -->
      <%= yield :sidebar_content %>
      <!-- end of sidebar-wrapper -->

      <!-- Page Content -->
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-1 col-xs-1">
              <a href="" id="menu-toggle"><%= fa_icon "bars" %></a>
            </div>
            <div class="col-md-6 col-sm-10 col-xs-offset-1 col-xs-10 min-margin">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
      <!-- end of page content -->
    </div>

  </body>
</html>

app/views/layouts/static_home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/feedback_wrapper' %>
    <%= yield %>

  </body>
</html>

app/views/messages/_message.html.erb
<div class="msg">
  <% if message.user == current_user %>
    <%= render partial: 'messages/message_by_current_user', locals: { message: message } %>
  <% else %>
    <%= render partial: 'messages/message_by_others', locals: { message: message } %>
  <% end %>
</div>

app/views/messages/_message_by_current_user.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-9 col-sm-offset-3 col-sm-9 col-xs-offset-3 col-xs-9">
    <div class="msg-frame msg-by-me">
      <div class="row">
        <div class="col-md-9 col-sm-9 col-xs-8 leave-left">
          <div class="row">
            <span class="msg-body">
              <%= message.body %>
            </span>
          </div>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-4">
          <div class="middle-gravatar">
            <%= link_to profile_path(message.user) do %>
              <%= gravatar_for message.user %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
<div class="time by-me">
  <%= message.timestamp %>
</div>

app/views/messages/_message_by_others.html.erb
<div class="row">
  <div class="col-md-9 col-sm-9 col-xs-9">
    <div class="msg-frame">
      <div class="row">
        <div class="col-md-3 col-sm-3 col-xs-4">
          <div class="middle-gravatar">
            <%= link_to profile_path(message.user) do %>
              <%= gravatar_for message.user %>
            <% end %>
          </div>
        </div>
        <div class="col-md-9 col-sm-9 col-xs-8 leave-right">
          <div class="row">
            <%= link_to profile_path(message.user) do %>
              <span class="detail"><%= message.user.name.capitalize %></span>
            <% end %>
          </div>

          <div class="row">
            <span class="msg-body">
              <%= message.body %>
            </span>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="time">
  <%= message.timestamp %>
</div>

app/views/shared/_errors.html.erb
<% if item.errors.any? %>
  <div class="error-msgs">
    <h2><%= pluralize(item.errors.count, "error") %></h2>
    <ul>
      <% item.errors.messages.each do |msg| %>
        <% msg.last.each do |detail| %>
          <li><%= msg.first.capitalize %>: <%= detail.capitalize %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feedback_wrapper.html.erb
<% if notice %>
  <div class="notice_wrapper">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert_wrapper">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>
    ©2016 Join. All Rights Reserved.
  </p>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed " data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Join', root_path, class: 'navbar-brand' %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to current_user.name.capitalize, profile_path(current_user) %>
            </li>

            <% if current_user.has_role?("Admin") %>
              <li>
                <%= link_to "Admin Panel", admin_root_path %>
              </li>
            <% end %>

            <li>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Sign in', new_user_registration_path %>
            </li>
            <li>
              <%= link_to 'Log in', new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/static_pages/home.html.erb
<div id="background">
  <div class="content">
    <div class="slogan">
      <p><span id="brand">JOIN</span> us &</p>
      <p>Communicate with the <%= link_to 'World', chat_rooms_path %> !!!</p>
    </div>

    <div class="btn-list">
      <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-highlight btn-ex' %>
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-highlight btn-ex btn-white' %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <div class="profile">

      <%= gravatar_for current_user %>
      <div class="user-detail">
        <p><%= current_user.name.capitalize %></p>
        <p><%= current_user.email %></p>
      </div>

      <div class="row">
        <div class="col-md-offset-4 col-md-4 col-sm-offset-4 col-sm-4 col-xs-offset-4 col-xs-4">
          <%= link_to 'Edit', edit_user_registration_path, class: 'btn btn-highlight' %>
        </div>
      </div>
    </div>
  </div>
</div>